version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: e2e-rabbitMq
    networks:
      - e2e-network

  rest:
    container_name: e2e-rest
    image: rest-service
    environment:
      - RABBIT_MQ_HOSTNAME=rabbitMq
    ports:
      - 8181:8181
    networks:
      - e2e-network
    depends_on:
      - rabbitMq

  token:
    container_name: e2e-token
    image: token-service
    environment:
      - RABBIT_MQ_HOSTNAME=rabbitMq
    networks:
      - e2e-network
    depends_on:
      - rabbitMq

networks:
  e2e-network: